### ISSUE TITLE
2024.02.29

### ISSUE THREAD

**Issue by seanmcilroy29** [Green-Software-Foundation/standards-wg#103]
----
## 2024.02.29 Agenda/Minutes
--- 
Time 1600 (GMT) - See the time in your [timezone](https://everytimezone.com/s/a8399b00)

- Co-Chair - Henry Richards (WattTime)
- Co-Chair - Naveen Balani - (Accenture) 
- Co-Chair – Abhishek Gupta (BCG)
- Convener – Sean Mcilroy (Linux Foundation)

## Antitrust Policy
Joint Development Foundation meetings may involve participation by industry competitors, and the Joint Development Foundation intends to conduct all of its activities in accordance with applicable antitrust and competition laws. It is, therefore, extremely important that attendees adhere to meeting agendas and be aware of and not participate in any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

If you have questions about these matters, please contact your company counsel or counsel to the Joint Development Foundation, DLA Piper.

## Recordings
WG agreed to record all [Meetings](https://docs.google.com/document/d/1WeRybJv8a8vunyRe9AawSqP0feVfe2PJ0KKiAGkI7kQ/edit). This meeting recording will be available until the next scheduled meeting.

## Roll Call 
Please *add 'Attended'* to this issue during the meeting to denote attendance.

Any untracked attendees will be added by the GSF team below:
- Full Name, Affiliation, (optional) GitHub username

## Agenda
- [x] Approve agenda
- [x] Approve [previous Meeting Minutes](https://github.com/Green-Software-Foundation/standards_wg/issues?q=is%3Aopen+is%3Aissue+label%3AAgenda%2FMinutes)

## Use case Submission Review
- [CAST - SCI to measure the improvement in CO2 emissions when decarbonizing software](https://github.com/Green-Software-Foundation/sci-guide/issues/60)

## GreenAI - Discussion Continued - Henry / Thomas 
- [x] Green AI project briefing, which includes:
- Executive Summary
- Design Principles
- Description of the Three Tenets
- Links to Discussions
- Next Steps
[Green AI Project Proposal Early Brief.pdf](https://github.com/Green-Software-Foundation/greenAI/files/14441215/Green.AI.Project.Proposal.Early.Brief.pdf)

### Project Review updates

- [x] [Transforming Organisational Software Sustainability](https://github.com/Green-Software-Foundation/toss) - **Pindy**
    - Project to be aligned with; 
      - [Maturity Matrix](https://github.com/Green-Software-Foundation/green-software-maturity-matrix) with the project.
      - Rubric project donated by Indeed

- [x] [Software Carbon Efficiency Rating](https://github.com/Green-Software-Foundation/standards-wg/issues/90) - **Chris**
    - [Baseline Spec](https://github.com/Green-Software-Foundation/scer/blob/Dev/Software_Carbon_Efficiency_Rating/Software_Carbon_Efficiency_Rating_Specification.md)
    - [Spec Development Proposal and Focus Areas](https://github.com/Green-Software-Foundation/scer/issues/19)
> [SCER Working Group (WG)](https://github.com/Green-Software-Foundation/scer) is exploring the use case for SCER standard for LLM (Large Language Models) in generative AI.

### Project Updates
- [x] [SCI](https://github.com/Green-Software-Foundation/standards-wg/issues/93) 
   - New SCI webpage - https://sci.greensoftware.foundation/
- [x] [Real-Time Cloud](https://github.com/Green-Software-Foundation/standards-wg/issues/89) - **Adrian**
    - the project has agreed to define the headers from the [GSF Real-Time Cloud Renewable Energy Percentage](https://docs.google.com/spreadsheets/d/1RKjD4CuI5bd7JTj-9Mi1-ZhTIc6OW7TH9hUvLPbLsPA/edit#gid=0) spreadsheet.
    - [collaboration document](https://docs.google.com/document/d/10sfRbx2lR18I02oNChaLYwc_ZgdtmSh0JyDerNloKGQ/edit#heading=h.4fr2qsg1jh7y)t to create the initial header explanations.
- [x] [sci-guide](https://github.com/Green-Software-Foundation/standards-wg/issues/92) - **Navveen**
 
## ISO - Sean
- [x] ISO placeholder now available, before its publication- https://www.iso.org/standard/86612.html
> Final draft now in publication after being signed off

## Article R&A peer review
- [x] Nothing submitted for review

**Note:** 
[WG use case template submission](https://github.com/Green-Software-Foundation/sci-guide/issues/new?assignees=atg-abhishek%2C+Henry-WattTime%2C+navveenb%2C+srini1978&labels=Case-study+submissions&template=case-study-template.md&title=Case-study+submissions) - After submitting this issue, your use case will be submitted to the WG Agenda for discussion.
[Article submission](https://github.com/Green-Software-Foundation/writers/issues/new?assignees=&labels=articles&template=new-article-proposal.md&title=%5BArticle%5D+A+proposed+name+for+this+article+or+topics) - Once you submit this issue, it will be assigned to the GSF Editor to review.

## Future meeting Agenda submissions
- [x] If you have any Agenda submissions, please let Sean know via email sean@greensoftware.foundation or [open an Issue](https://github.com/Green-Software-Foundation/standards-wg/issues)

## Next Meeting
- [x] 14th Mar

## Adjourn 
- [ ] Motion to adjourn
--------

## Meeting Action Items / Standing Agenda / Future Agenda submissions
- [ ] Standing Agenda Item - First meeting of each month - Member Introductions / Buddy-buddy meeting to help new members understand the work in the SWG.
- [ ] Standing Agenda Item - First meeting of each month - 5 - 10 min round up of what is happening across the other WG

**Comment by tholewis** [comment]
Hey folks, I didn't want to edit the agenda and mess it up and also we are having unusual weather, so I thought I'd provide a quick link to the Green AI Project document entry I made at https://github.com/Green-Software-Foundation/greenAI/issues/1 just in case the weather gets worse. 

The [first comment](https://github.com/Green-Software-Foundation/greenAI/issues/1#issuecomment-1970159483) links to the document I mentioned last meeting I would create for this meeting that provides an overview of the project. It not an end-to-end project plan but provides greater detail that we can share with others, provides some scope, and it will continue to be iterated on. 

I also [added a comment](https://github.com/Green-Software-Foundation/greenAI/issues/1#issuecomment-1970164655) for the next steps to discuss at this meeting if folks are interested as well. Look forward to talking to folks about it! 🌳

**Comment by marcoshidalgonunes-avanade** [comment]
Attended

**Comment by Henry-WattTime** [comment]
Attended

**Comment by tholewis** [comment]
Attended! 🌳

**Comment by kapokasa** [comment]
Attended

**Comment by seanmcilroy29** [comment]
Attended

**Comment by navveenb** [comment]
attended

**Comment by tmcclell** [comment]
attended

**Comment by mvaltas** [comment]
attended

**Comment by seanmcilroy29** [comment]
**MoM**
**Creating a new project proposal for a sustainability initiative.**
Thomas suggests using a RACI model to clarify responsibilities and enhance communication among team members. Henry inquires about an update on the three tenets of billing and resources, to which Thomas responds that John has finished the document but still needs to confirm availability. Thomas is scheduling a call for the core team to discuss the three tenets of the project and invites others to join. Sean volunteers to create a Zoom link and send it to attendees and also recommends using an existing repository for the project.

**AI position summary and resource allocation.**
Thomas and Henry discussed the AI project plan. Thomas proposed using the document they had as an update for the community working group and policy group at their next meeting. Henry agreed and suggested that some conversations with the policy folks could run concurrently. They also discussed the involvement of AI experts in the process. Thomas suggested bringing in AI experts once the team had a clear direction and outline rather than at the beginning of the project. He also recommended using small language models as a more carbon-intensive solution for AI projects, citing technical credibility as a priority. Henry suggested writing a document to outline the subject areas or paragraphs for the experts to react to, prioritise tasks, and focus on smaller, more agile projects.

- [Green AI Project document](https://github.com/Green-Software-Foundation/greenAI/issues/1) 
- [Green AI Discussion](https://github.com/Green-Software-Foundation/greenAI/issues/1#issuecomment-1970159483) 
- [Next Steps](https://github.com/Green-Software-Foundation/greenAI/issues/1#issuecomment-1970164655)

**Action Items**
- [ ] Members - Review the Green AI principles document before next Thursday's meeting
- [ ] Create a shortened brief version of the green AI principles document and include it in the following newsletter
- [ ] Ping Urs to see if he has completed the article on billing principles
- [ ] Thomas - Add the Green AI core team meeting to the calendar and distribute the Zoom link
