### ISSUE TITLE
2024.03.28

### ISSUE THREAD

**Issue by seanmcilroy29** [Green-Software-Foundation/standards-wg#105]
----
## 2024.03.28 Agenda/Minutes
--- 
Time 1600 (GMT) - See the time in your [timezone](https://everytimezone.com/s/a8399b00)

- Co-Chair - Henry Richards (WattTime)
- Co-Chair - Naveen Balani - (Accenture) 
- Co-Chair – Abhishek Gupta (BCG)
- Convener – Sean Mcilroy (Linux Foundation)

## Antitrust Policy
Joint Development Foundation meetings may involve participation by industry competitors, and the Joint Development Foundation intends to conduct all of its activities in accordance with applicable antitrust and competition laws. It is, therefore, extremely important that attendees adhere to meeting agendas and be aware of and not participate in any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

If you have questions about these matters, please contact your company counsel or counsel to the Joint Development Foundation, DLA Piper.

## Recordings
WG agreed to record all [Meetings](https://docs.google.com/document/d/1WeRybJv8a8vunyRe9AawSqP0feVfe2PJ0KKiAGkI7kQ/edit). This meeting recording will be available until the next scheduled meeting.

## Roll Call 
Please *add 'Attended'* to this issue during the meeting to denote attendance.

Any untracked attendees will be added by the GSF team below:
- Full Name, Affiliation, (optional) GitHub username

## Agenda
- [x] Approve agenda
- [x] Approve [previous Meeting Minutes](https://github.com/Green-Software-Foundation/standards_wg/issues?q=is%3Aopen+is%3Aissue+label%3AAgenda%2FMinutes)

## GreenAI - Discussion Continued - Henry / Thomas 
- [x] Green AI project briefing, which includes:
- Next Steps
[Green AI Project Proposal Early Brief.pdf](https://github.com/Green-Software-Foundation/greenAI/files/14441215/Green.AI.Project.Proposal.Early.Brief.pdf)

## WG Discussion
- [ ] Add [sustainability Metrics to Semantic Conventions](https://github.com/open-telemetry/community/issues/2020)
> Brendan Kamp (Re-cinq)

### Project Review updates
- [ ] [Transforming Organisational Software Sustainability](https://github.com/Green-Software-Foundation/toss) - **Pindy**
    - Project to be aligned with; 
      - [Maturity Matrix](https://github.com/Green-Software-Foundation/green-software-maturity-matrix) with the project.
      - Rubric project donated by Indeed

- [ ] [Software Carbon Efficiency Rating](https://github.com/Green-Software-Foundation/standards-wg/issues/90) - **Chris**
    - [Baseline Spec](https://github.com/Green-Software-Foundation/scer/blob/Dev/Software_Carbon_Efficiency_Rating/Software_Carbon_Efficiency_Rating_Specification.md)
    - [Spec Development Proposal and Focus Areas](https://github.com/Green-Software-Foundation/scer/issues/19)
> [SCER Working Group (WG)](https://github.com/Green-Software-Foundation/scer) is exploring the use case for SCER standard for LLM (Large Language Models) in generative AI.
- [ ] [Real-Time Cloud](https://github.com/Green-Software-Foundation/standards-wg/issues/89) - **Adrian**
    - Defining the [GSF Real-Time Cloud Renewable Energy Percentage](https://docs.google.com/spreadsheets/d/1RKjD4CuI5bd7JTj-9Mi1-ZhTIc6OW7TH9hUvLPbLsPA/edit#gid=0) spreadsheet.
    - [collaboration document](https://docs.google.com/document/d/10sfRbx2lR18I02oNChaLYwc_ZgdtmSh0JyDerNloKGQ/edit#heading=h.4fr2qsg1jh7y)t to create the initial header explanations.
 
## ISO - Sean
- [ ] ISO placeholder now available, before its publication- https://www.iso.org/standard/86612.html

## Articles
- [ ] [DECARBONIZING SOFTWARE: HOW CAST APPLIED THE SCI METRIC TO MAKE A DIFFERENCE](https://greensoftware.foundation/articles/decarbonizing-software-how-cast-applied-the-sci-metric)
### For Review
- [ ] [Decarbonizing Software: How CAST applied the SCI Metric to Make a Difference](https://docs.google.com/document/d/1xmcUjH9DeD2DVJ1fo8cGdD8G9puQr_2C/edit)
- [ ] [Lifecycle Assessment (LCA) for Software Applications using SCI and Impact Framework](https://docs.google.com/document/d/1YiUqflm8Gh7R10_acrWoHjRc_X0uZfdG/edit) - Srini 

**Note:** 
[WG use case template submission](https://github.com/Green-Software-Foundation/sci-guide/issues/new?assignees=atg-abhishek%2C+Henry-WattTime%2C+navveenb%2C+srini1978&labels=Case-study+submissions&template=case-study-template.md&title=Case-study+submissions) - After submitting this issue, your use case will be submitted to the WG Agenda for discussion.
[Article submission](https://github.com/Green-Software-Foundation/writers/issues/new?assignees=&labels=articles&template=new-article-proposal.md&title=%5BArticle%5D+A+proposed+name+for+this+article+or+topics)—Once you submit this issue, it will be assigned to the GSF Editor for review.

## Future meeting Agenda submissions
- [ ] If you have any Agenda submissions, please let Sean know via email at sean@greensoftware.foundation or [open an Issue](https://github.com/Green-Software-Foundation/standards-wg/issues)

## Next Meeting
- [ ] 11 Apr
> The US is now on daylight saving, and Europe will move to daylight saving on 31 March.

## Adjourn 
- [x] Motion to adjourn
--------

### Meeting Action Items / Standing Agenda / Future Agenda submissions

**Action Items**
- [x] Share detailed calculation slides from the Cast case study with the working group.
> Completed
- [x] Send calculation slides to Sean for case study publication.
> Added to Issue #60 - [CAST case study - using SCI and software intelligence to estimate CO2 emissions.pdf](https://github.com/Green-Software-Foundation/sci-guide/files/14721312/CAST.case.study.-.using.SCI.and.software.intelligence.to.estimate.CO2.emissions.pdf)
- [x] Reach out to Namrata to schedule an interview and overview of the Cast case study for publication.
> Completed - https://greensoftware.foundation/articles/decarbonizing-software-how-cast-applied-the-sci-metric

### Standing Agenda / Future Agenda submissions
- [ ] Standing Agenda Item: The First meeting of each month is a member Introduction / Buddy-buddy meeting to help new members understand the work in the SWG.
- [ ] Standing Agenda Item - First meeting of each month - 5 - 10 min round up of what is happening across the other WG

**Comment by marcoshidalgonunes-avanade** [comment]
Attended

**Comment by navveenb** [comment]
attended
