### ISSUE TITLE
2024.04.11

### ISSUE THREAD

**Issue by seanmcilroy29** [Green-Software-Foundation/standards-wg#107]
----
## 2024.04.11 Agenda/Minutes
--- 
Time 1600 (GMT) - See the time in your [timezone](https://everytimezone.com/s/a8399b00)

- Co-Chair - Henry Richards (WattTime)
- Co-Chair - Naveen Balani - (Accenture) 
- Co-Chair – Abhishek Gupta (BCG)
- Convener – Sean Mcilroy (Linux Foundation)

## Antitrust Policy
Joint Development Foundation meetings may involve participation by industry competitors, and the Joint Development Foundation intends to conduct all of its activities in accordance with applicable antitrust and competition laws. It is, therefore, extremely important that attendees adhere to meeting agendas and be aware of and not participate in any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

If you have questions about these matters, please contact your company counsel or counsel to the Joint Development Foundation, DLA Piper.

## Recordings
WG agreed to record all [Meetings](https://docs.google.com/document/d/1WeRybJv8a8vunyRe9AawSqP0feVfe2PJ0KKiAGkI7kQ/edit). This meeting recording will be available until the next scheduled meeting.

## Roll Call 
Please *add 'Attended'* to this issue during the meeting to denote attendance.

Any untracked attendees will be added by the GSF team below:
- Full Name, Affiliation, (optional) GitHub username

## Agenda
- [x] Approve agenda
- [x] Approve [previous Meeting Minutes](https://github.com/Green-Software-Foundation/standards_wg/issues?q=is%3Aopen+is%3Aissue+label%3AAgenda%2FMinutes)

## ISO Publication- Sean
ISO has now published the SCI - https://www.iso.org/standard/86612.html
### PRs for Review and Approval
- [x] [SCI aligning with ISO v1.0 approved changes](https://github.com/Green-Software-Foundation/sci/pull/377)
- [x] [Approved Dev v1.1](https://github.com/Green-Software-Foundation/sci/pull/378/files)
- [x] [Updating Main from v1.0 to v1.1](https://github.com/Green-Software-Foundation/sci/pull/379)

## GreenAI - Discussion Continued - Henry / Thomas 
- [ ] Green AI project briefing, which includes:
- Next Steps continued
[Green AI Project Proposal Early Brief.pdf](https://github.com/Green-Software-Foundation/greenAI/files/14441215/Green.AI.Project.Proposal.Early.Brief.pdf)

## WG Discussion
- [x] Add [sustainability Metrics to Semantic Conventions](https://github.com/open-telemetry/community/issues/2020)
> discussed at the last meeting

### Project Review updates
- [ ] [Transforming Organisational Software Sustainability](https://github.com/Green-Software-Foundation/toss) - **Pindy**
    - Project to be aligned with; 
      - [Maturity Matrix](https://github.com/Green-Software-Foundation/green-software-maturity-matrix) with the project.
```
Now Progressing to phase 2
```
- [ ] [Software Carbon Efficiency Rating](https://github.com/Green-Software-Foundation/standards-wg/issues/90) - **Chris**
    - [Baseline Spec](https://github.com/Green-Software-Foundation/scer/blob/Dev/Software_Carbon_Efficiency_Rating/Software_Carbon_Efficiency_Rating_Specification.md)
    - [Spec Development Proposal and Focus Areas](https://github.com/Green-Software-Foundation/scer/issues/19)
    - [SCER Working Group (WG)](https://github.com/Green-Software-Foundation/scer) is exploring the use case for SCER standard for LLM (Large Language Models) in generative AI.
```
Note: Chris will review the Spec at the next meeting before submitting it for a WG review. 
Members are invited to review and comment directly on the SCER project.
```

- [ ] [Real-Time Cloud](https://github.com/Green-Software-Foundation/standards-wg/issues/89) - **Adrian**
    - Defining the [GSF Real-Time Cloud Renewable Energy Percentage](https://docs.google.com/spreadsheets/d/1RKjD4CuI5bd7JTj-9Mi1-ZhTIc6OW7TH9hUvLPbLsPA/edit#gid=0) spreadsheet.
    - [collaboration document](https://docs.google.com/document/d/10sfRbx2lR18I02oNChaLYwc_ZgdtmSh0JyDerNloKGQ/edit#heading=h.4fr2qsg1jh7y)t to create the initial header explanations.
- [ ] [sci-guide](https://github.com/Green-Software-Foundation/standards-wg/issues/92) - **Navveen**

## Articles
- [ ] [DECARBONIZING SOFTWARE: HOW CAST APPLIED THE SCI METRIC TO MAKE A DIFFERENCE](https://greensoftware.foundation/articles/decarbonizing-software-how-cast-applied-the-sci-metric)

### For Review
- [ ] [Lifecycle Assessment (LCA) for Software Applications using SCI and Impact Framework](https://docs.google.com/document/d/1YiUqflm8Gh7R10_acrWoHjRc_X0uZfdG/edit) - Srini 

**Note:** 
[WG use case template submission](https://github.com/Green-Software-Foundation/sci-guide/issues/new?assignees=atg-abhishek%2C+Henry-WattTime%2C+navveenb%2C+srini1978&labels=Case-study+submissions&template=case-study-template.md&title=Case-study+submissions) - After submitting this issue, your use case will be submitted to the WG Agenda for discussion.
[Article submission](https://github.com/Green-Software-Foundation/writers/issues/new?assignees=&labels=articles&template=new-article-proposal.md&title=%5BArticle%5D+A+proposed+name+for+this+article+or+topics)—Once you submit this issue, it will be assigned to the GSF Editor for review.

## Future meeting Agenda submissions
- [ ] If you have any Agenda submissions, please let Sean know via email at sean@greensoftware.foundation or [open an Issue](https://github.com/Green-Software-Foundation/standards-wg/issues)

## Next Meeting
- [ ] 25 Apr

## Adjourn 
- [ ] Motion to adjourn
--------

### Standing Agenda / Future Agenda submissions
- [ ] Standing Agenda Item: The First meeting of each month is a member Introduction / Buddy-buddy meeting to help new members understand the work in the SWG.
- [ ] Standing Agenda Item - First meeting of each month - 5 - 10 min round up of what is happening across the other WG

**Comment by navveenb** [comment]
@seanmcilroy29 , Please add the SCI guide to WG Project discussions.

**Comment by llhardy1A** [comment]
Attended

**Comment by Henry-WattTime** [comment]
Attended

**Comment by marcoshidalgonunes-avanade** [comment]
Attended

**Comment by ash-ara** [comment]
Attended

**Comment by chrisxie-fw** [comment]
attended

**Comment by kapokasa** [comment]
attended

**Comment by PindyBhullar** [comment]
Attended

**Comment by tdigeser91** [comment]
Attended

**Comment by seanmcilroy29** [comment]
**MoM**

Henry opens the meeting at 1600 BST

**Updating a standard to align with ISO requirements, including minor text edits and typo confirmation.**
Sean outlines that the main GitHub branch requires updating to align with the approved ISO document. He then discussed the process and importance of versioning for an upcoming release. During the meeting, Filippo pointed out a potential spelling mistake in line 249 of the new version. Sean and Henry then discussed minor text edits that needed to be made for an ISO standard. Henry motioned an editorial change, which the WG approved. Henry approved the changes and suggested that the WG push version 1.0, with text edits made in the dev branch for version 1.1.


Sean proposed creating a new version of the document, version 1.1. Henry agrees but emphasises the importance of reviewing and confirming the changes before moving forward. Sean thanked the WG for the quick ISO standard development and highlighted their hard work. Sean plans to create a viewable diffs PR for the WG to review before the 18th Apr. Once Approved, v1.1 will be submitted to ISO. 

**SCI PR release** 
Namrata shared a draft document on carbon usage and is seeking feedback from Henry and Pindy. Henry and Pindy discuss the document's clarity, timeline, and the need for track changes or suggestions.

[SCI](https://github.com/Green-Software-Foundation/organisation-usage-of-software-emissions) Project Updates

[Transforming Organisational Software Sustainability](https://github.com/Green-Software-Foundation/organisation-usage-of-software-emissions): Pindy provides an update on the project.

**SCER:** Chris is asked to provide an overview of the CDR, which the team has worked on, the baseline specification for AI, the green AI initiative, and review work. Chris seeks input and participation on baseline specification for large language models. Chris shares update on standardisation specifications for LLM, including baseline and derived classes, and seeks feedback from the community. Henry and Chris discuss defining "green AI" for the industry, with Chris proposing a definition.

**Action Items**
- [ ] Review draft press release about ISO publication by July 18th and provide feedback/comments.
- [ ] Provide an overview of SCER work at the next meeting, including developing an LLM use case.
- [ ] Participate in a discussion on defining "Green AI" in LF AI & Data working group.
- [ ] Help structure ideas on the Tackling Operational Sustainability Strategically Miro board and develop a framework.
- [ ] Review v1.0 and v1.1 change bars before merging PR#379
