### ISSUE TITLE
2024.04.25

### ISSUE THREAD

**Issue by seanmcilroy29** [Green-Software-Foundation/standards-wg#108]
----
## 2024.04.25 Agenda/Minutes
--- 
Time 1600 (GMT) - See the time in your [timezone](https://everytimezone.com/s/a8399b00)

- Co-Chair - Henry Richards (WattTime)
- Co-Chair - Naveen Balani - (Accenture) 
- Co-Chair – Abhishek Gupta (BCG)
- Convener – Sean Mcilroy (Linux Foundation)

## Antitrust Policy
Joint Development Foundation meetings may involve participation by industry competitors, and the Joint Development Foundation intends to conduct all of its activities in accordance with applicable antitrust and competition laws. It is, therefore, extremely important that attendees adhere to meeting agendas and be aware of and not participate in any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

If you have questions about these matters, please contact your company counsel or counsel to the Joint Development Foundation, DLA Piper.

## Recordings
WG agreed to record all [Meetings](https://docs.google.com/document/d/1WeRybJv8a8vunyRe9AawSqP0feVfe2PJ0KKiAGkI7kQ/edit). This meeting recording will be available until the next scheduled meeting.

## Roll Call 
Please *add 'Attended'* to this issue during the meeting to denote attendance.

Any untracked attendees will be added by the GSF team below:
- Full Name, Affiliation, (optional) GitHub username

## Agenda
- [x] Approve agenda
- [x] Approve [previous Meeting Minutes](https://github.com/Green-Software-Foundation/standards_wg/issues?q=is%3Aopen+is%3Aissue+label%3AAgenda%2FMinutes)

## ISO Publication- Sean
- [x] ISO has now published the SCI v1.0 - https://www.iso.org/standard/86612.html
- [x] SCI v1.1 approved and pushed to main
- [x] PR announcement for v1.0 & v1.1 circulated

## [Software Carbon Efficiency Rating - Review](https://github.com/Green-Software-Foundation/scer) - **Chris Xie**
- [ ] Discussion/review focuses on the LLM and proposed methodology for LLM in generative AI.

## GreenAI - Discussion Continued - Henry / Thomas 
- [ ] Green AI project briefing, which includes:
- Next Steps continued
[Green AI Project Proposal Early Brief.pdf](https://github.com/Green-Software-Foundation/greenAI/files/14441215/Green.AI.Project.Proposal.Early.Brief.pdf)

### Project Review updates
- [ ] [Transforming Organisational Software Sustainability](https://github.com/Green-Software-Foundation/toss) - **Pindy**
    - Project to be aligned with; 
      - [Maturity Matrix](https://github.com/Green-Software-Foundation/green-software-maturity-matrix) with the project.
- [ ] [Real-Time Cloud](https://github.com/Green-Software-Foundation/standards-wg/issues/89) - **Adrian**
    - Defining the [GSF Real-Time Cloud Renewable Energy Percentage](https://docs.google.com/spreadsheets/d/1RKjD4CuI5bd7JTj-9Mi1-ZhTIc6OW7TH9hUvLPbLsPA/edit#gid=0) spreadsheet.
    - [collaboration document](https://docs.google.com/document/d/10sfRbx2lR18I02oNChaLYwc_ZgdtmSh0JyDerNloKGQ/edit#heading=h.4fr2qsg1jh7y)t to create the initial header explanations.
- [ ] [sci-guide](https://github.com/Green-Software-Foundation/standards-wg/issues/92) - **Navveen**

## Articles
- [ ] [Software Carbon Intensity (SCI) Specification Achieves ISO Standard Status, Advancing Green Software Development](https://docs.google.com/document/d/1BuH6fHeWqqI7_cy7l1mvmts_V_ZC9jpY0B5wunt07hg/edit#heading=h.h1uyi8wrebop)

### For Review
- [ ] [Lifecycle Assessment (LCA) for Software Applications using SCI and Impact Framework](https://docs.google.com/document/d/1YiUqflm8Gh7R10_acrWoHjRc_X0uZfdG/edit) - Srini 

**Note:** 
[WG use case template submission](https://github.com/Green-Software-Foundation/sci-guide/issues/new?assignees=atg-abhishek%2C+Henry-WattTime%2C+navveenb%2C+srini1978&labels=Case-study+submissions&template=case-study-template.md&title=Case-study+submissions) - After submitting this issue, your use case will be submitted to the WG Agenda for discussion.
[Article submission](https://github.com/Green-Software-Foundation/writers/issues/new?assignees=&labels=articles&template=new-article-proposal.md&title=%5BArticle%5D+A+proposed+name+for+this+article+or+topics)—Once you submit this issue, it will be assigned to the GSF Editor for review.

## Future meeting Agenda submissions
- [ ] If you have any Agenda submissions, please let Sean know via email at sean@greensoftware.foundation or [open an Issue](https://github.com/Green-Software-Foundation/standards-wg/issues)

## Next Meeting
- [ ] 09th May

## Adjourn 
- [ ] Motion to adjourn
--------

### Previous meeting Action Items 
- [ ] Review draft press release about ISO publication by July 18th and provide feedback/comments.
- [ ] Provide an overview of SCER work at the next meeting, including developing an LLM use case.
- [ ] Participate in a discussion on defining "Green AI" in LF AI & Data working group.
- [ ] Help structure ideas on the Tackling Operational Sustainability Strategically Miro board and develop a framework.
- [ ] Review v1.0 and v1.1 change bars before merging PR#379

### Standing Agenda / Future Agenda submissions
- [ ] Standing Agenda Item: The First meeting of each month is a member Introduction / Buddy-buddy meeting to help new members understand the work in the SWG.
- [ ] Standing Agenda Item - First meeting of each month - 5 - 10 min round up of what is happening across the other WG

**Comment by GadhuNTTDATA** [comment]
Attended

**Comment by llhardy1A** [comment]
Attended

**Comment by tholewis** [comment]
Attended! 🌳

**Comment by Henry-WattTime** [comment]
Attended

**Comment by seanmcilroy29** [comment]
Attended

**Comment by chrisxie-fw** [comment]
attended

**Comment by navveenb** [comment]
attended

**Comment by kapokasa** [comment]
attended
