### ISSUE TITLE
2022.11.10

### ISSUE THREAD

**Issue by seanmcilroy29** [Green-Software-Foundation/standards-wg#30]
----
## 2022.11.10 Agenda/Minutes
--- 
Time 1600 (GMT) - See the time in your [timezone](https://everytimezone.com/s/a8399b00)

- Co-Chair – Abhishek Gupta (BCG)
- Co-Chair - Henry Richards (WattTime)
- Convener – Sean Mcilroy (Linux Foundation)

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
WG agreed to record all [Meetings](https://docs.google.com/document/d/1WeRybJv8a8vunyRe9AawSqP0feVfe2PJ0KKiAGkI7kQ/edit). This meeting recording will be available until the next scheduled meeting

### Roll Call 
Please *add 'Attended'* to this issue during the meeting to denote attendance.

Any untracked attendees will be added by the GSF team below:
- Full Name, Affiliation, (optional) GitHub username

## Agenda
- [x] Convene & Roll Call 
- [x] Approve agenda
> Sean reviews the agenda - Tammy motions to approve - no objections - Agenda agreed
- [x] Approve [previous Meeting Minutes](https://github.com/Green-Software-Foundation/standards_wg/issues?q=is%3Aopen+is%3Aissue+label%3AAgenda%2FMinutes)
> Tammy motions to approve - no objections - Mintues agreed

## Case Study Demo
- [x] Green-Software-Foundation/software_carbon_intensity#22 
> Tammy to lead

Collaborative use case with Dow and Microsoft performed by Tammy McClellan and Srinivasan Rakhunathan from Microsoft. Eric Friedeberg, Brandon Smith, and Samantha Beauchamp from Dow.

Solution chosen: is a current solution in development and is the measurement of carbon in both Neo4J and TigerGraph graph databases. Information was collected via load tests by calling an API deployed in an app service.

- [x] see https://github.com/Green-Software-Foundation/sci-data/issues/31

## Case Study Update Review 
- [x] Green-Software-Foundation/software_carbon_intensity#18 
> Navveen informs the WG that Accenture intends to conduct a demo at the next meeting
- [x] Green-Software-Foundation/dictionary#5 
> Notes added to issue
- [x] Green-Software-Foundation/software_carbon_intensity#20
Pindy provides an update on the UBS use case submission 
- [x] Green-Software-Foundation/software_carbon_intensity#21 
> No updates
- [x] Green-Software-Foundation/software_carbon_intensity#23 
> No updates
### [Discussions](https://github.com/Green-Software-Foundation/software_carbon_intensity/discussions) **[Deferred]**

- [ ] 1. https://github.com/Green-Software-Foundation/software_carbon_intensity/discussions/334
- Discussion regarding **Carbon Data Interchange** to determine if there's scope for a project, prior to submitting a PRFAQ

- [ ] 2. https://github.com/Green-Software-Foundation/software_carbon_intensity/discussions/326
- Could this be something that is explored as a project under the aegis of the SWG?

- [ ] 3. https://github.com/Green-Software-Foundation/software_carbon_intensity/discussions/330
- roadmap for discussion post 1.0

- [ ] 4. https://github.com/Green-Software-Foundation/software_carbon_intensity/discussions/328

## Next SCI Version **[Deferred]**
  - [ ] Outline of what should be included in the next version

### [SCI open data](https://sci-data.greensoftware.foundation/) - Navveen/Srini
> Continue discussion from last week
- [x] Outline of scope for project and the Guidance pages

### SCI Guidance page 
- SCI Guidance submissions for the standard, explain the standard and answer recurring questions. 
  - [x] [SCI Guidance.md page](https://github.com/Green-Software-Foundation/sci-guidance/blob/main/guidance/guidance.md)
  - [x] [Issues](https://github.com/Green-Software-Foundation/sci-faq/issues) - All submitted FAQ's from the SCI repo have been moved across

### [Onboarding Guide](https://github.com/Green-Software-Foundation/standards_wg/blob/webpage_dev_for_submissions/docs/onboarding_guide.mdx)

- [x] https://github.com/Green-Software-Foundation/standards-wg/pull/25/files

```
Note: All webpage submissions must be against this branch `webpage_dev_for_submissions`
An onboarding guide for folks joining the Standards WG, what they should know/read/understand about the process and the spec.
```

> Henry reviews the onboarding PR and agrees to apply updates in preparation for the next meeting.

> AI: WG members to review submitted PR

### [Standards WG Webpage](https://standards.greensoftware.foundation)
- [x] Outline of content to be added

## [Software Carbon Intensity (SCI)](https://github.com/Green-Software-Foundation/software_carbon_intensity/blob/dev/Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md)
> Nothing to report

### [PRs](https://github.com/Green-Software-Foundation/software_carbon_intensity/pulls)
> Nothing to review

## Decarbonize Software event
- [x] [Event details](https://decarb.greensoftware.foundation/)
> Sean reminds the members of the upcoming Decarbonize software event

## AOB, Q&A 
- [x] Member request to move the meeting to an earlier time
Nothing added

## Next Meeting
- [x] 17 Nov
> Agreed

## Adjourn 
Tammy motions to adjourn - no objections - meeting adjourned
--------
## Meeting Action Items
- [ ] {add details here}

**Comment by SaraEmilyBergman** [comment]
Attended

**Comment by navveenb** [comment]
Attended

**Comment by PindyBhullar** [comment]
Attended

**Comment by llhardy1A** [comment]
Attended
