### ISSUE TITLE
2023.01.12

### ISSUE THREAD

**Issue by seanmcilroy29** [Green-Software-Foundation/standards-wg#38]
----
## 2023.01.12 Agenda/Minutes
--- 
Time 1600 (GMT) - See the time in your [timezone](https://everytimezone.com/s/a8399b00)

- Co-Chair – Abhishek Gupta (BCG)
- Co-Chair - Henry Richards (WattTime)
- Convener – Sean Mcilroy (Linux Foundation)

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
WG agreed to record all [Meetings](https://docs.google.com/document/d/1WeRybJv8a8vunyRe9AawSqP0feVfe2PJ0KKiAGkI7kQ/edit). This meeting recording will be available until the next scheduled meeting

### Roll Call 
Please *add 'Attended'* to this issue during the meeting to denote attendance.

Any untracked attendees will be added by the GSF team below:
- Full Name, Affiliation, (optional) GitHub username

## Agenda
- [x] Convene & Roll Call 
> Sean reviewed the agenda - Sarah motioned to approve - no objections agenda agreed
- [x] Approve agenda
> Sean agreed the previous meeting minutes - Gadhu motioned to approve - No objections minutes approved
- [x] Approve [previous Meeting Minutes](https://github.com/Green-Software-Foundation/standards_wg/issues?q=is%3Aopen+is%3Aissue+label%3AAgenda%2FMinutes)

## Introduction from new members
> No new members 

## [Discussions](https://github.com/Green-Software-Foundation/software_carbon_intensity/discussions)

- [x] 1. https://github.com/Green-Software-Foundation/software_carbon_intensity/discussions/337
> Comments added to discussion
- [x] 2. https://github.com/Green-Software-Foundation/software_carbon_intensity/discussions/330
> Comments added to discussion
- [x] 3. https://github.com/Green-Software-Foundation/software_carbon_intensity/discussions/328
> Comments added to discussion
- [x] 4. https://github.com/Green-Software-Foundation/software_carbon_intensity/discussions/339
> Comments added to discussion
- [x] 5. https://github.com/Green-Software-Foundation/software_carbon_intensity/issues/340
> Comments added to discussion

## Case Study Update Review
- [x] Green-Software-Foundation/software_carbon_intensity#20 
> Comments added to Issue
- [x] Green-Software-Foundation/software_carbon_intensity#21 
> Comments added to Issue
- [x] Green-Software-Foundation/software_carbon_intensity#23
> Comments added to Issue
- [x] https://github.com/Green-Software-Foundation/sci-data/issues/33
> Comments added to Issue

### Completed Case studies - Submitted questions to reivew?
- [x] https://github.com/Green-Software-Foundation/sci-data/issues/32
- [x] https://github.com/Green-Software-Foundation/sci-data/issues/31
- [x] Green-Software-Foundation/software_carbon_intensity#36 
- [x] Green-Software-Foundation/software_carbon_intensity#18 

### [SCI open data](https://sci-data.greensoftware.foundation/) - Navveen/Srini
- [x] Navveen provides an update on the progress of the SCI open data project

> AI: Sean to move over CS's to SCI Guidelines

### Project proposals
- [x] https://github.com/Green-Software-Foundation/software_carbon_intensity/discussions/334
> > Comments added to Issue

### [PRs](https://github.com/Green-Software-Foundation/software_carbon_intensity/pulls)
> Nothing to review

## AOB, Q&A 
 - [ ] Add standing Agenda Item - First meeting of each month - Member Introductions
 - [ ] Add standing Agenda Item - First meeting of each month - 5 - 10 min round up of what is happening across the other WG
 - [ ] Create article template for Use Case submitters to use. Articles will we published and circulated across the GSF networks

AI: Sean to action all submissions

## Next Meeting
- [x] 19 Jan 
> Agreed

## Adjourn 
- [x] Motion to adjourn

Gadhu motions to adjourn - no objections - meeting closed

No objections - meeting adjourned
--------
## Meeting Action Items

- [ ] move over CS's to SCI Guidelines 
- [ ] Standing Agenda Item - First meeting of each month - Member Introductions
- [ ] Standing Agenda Item - First meeting of each month - 5 - 10 min round up of what is happening across the other WG
- [ ] Create article template for Use Case submitters to use. Articles will we published and circulated across the GSF networks

**Comment by llhardy1A** [comment]
attended

**Comment by ciril-emaps** [comment]
Attended

**Comment by Henry-WattTime** [comment]
Attended

**Comment by GadhuNTTDATA** [comment]
Attended

**Comment by seanmcilroy29** [comment]
Attended

**Comment by kapokasa** [comment]
attended

**Comment by ikolaxis** [comment]
Attended

**Comment by benlogan** [comment]
Attended

**Comment by seanmcilroy29** [comment]
Action Items
- [ ] Agenda Item - First meeting of each month - Member Introductions 
- [ ] Agenda Item - First meeting of each month - 5 - 10 min round up of what is happening across the other WG
- [ ] Create article template for Use Case submitters to use. Articles will we published and circulated across the GSF networks

**Comment by navveenb** [comment]
attended
