### ISSUE TITLE
2023.12.07

### ISSUE THREAD

**Issue by seanmcilroy29** [Green-Software-Foundation/standards-wg#94]
----
## 2023.12.07 Agenda/Minutes
--- 
Time 1600 (GMT) - See the time in your [timezone](https://everytimezone.com/s/a8399b00)

- Co-Chair - Henry Richards (WattTime)
- Co-Chair - Naveen Balani - (Accenture) 
- Co-Chair – Abhishek Gupta (BCG)
- Convener – Sean Mcilroy (Linux Foundation)

## Antitrust Policy
Joint Development Foundation meetings may involve participation by industry competitors, and the Joint Development Foundation intends to conduct all of its activities in accordance with applicable antitrust and competition laws. It is, therefore, extremely important that attendees adhere to meeting agendas and be aware of and not participate in any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

If you have questions about these matters, please contact your company counsel or counsel to the Joint Development Foundation, DLA Piper.

## Recordings
WG agreed to record all [Meetings](https://docs.google.com/document/d/1WeRybJv8a8vunyRe9AawSqP0feVfe2PJ0KKiAGkI7kQ/edit). This meeting recording will be available until the next scheduled meeting.

## Roll Call 
Please *add 'Attended'* to this issue during the meeting to denote attendance.

Any untracked attendees will be added by the GSF team below:
- Full Name, Affiliation, (optional) GitHub username

## Agenda
- [x] Approve agenda
- [x] Approve [previous Meeting Minutes](https://github.com/Green-Software-Foundation/standards_wg/issues?q=is%3Aopen+is%3Aissue+label%3AAgenda%2FMinutes)

## Member Introductions
- [x] Opportunity for new members to introduce themselves

## WG Project updates - [Dashboard](https://github.com/Green-Software-Foundation/standards-wg/issues?q=is%3Aopen+is%3Aissue+label%3A%22Project+Update%22)

- [x] [Organisation usage of Software Emissions](https://github.com/Green-Software-Foundation/standards-wg/issues/91) - update
- [x] [SCI](https://github.com/Green-Software-Foundation/standards-wg/issues/93) - update
- [x] [Software Carbon Efficiency Rating](https://github.com/Green-Software-Foundation/standards-wg/issues/90) - update
- [x] [Real-Time Cloud](https://github.com/Green-Software-Foundation/standards-wg/issues/89) - update
- [x] [sci-guide](https://github.com/Green-Software-Foundation/standards-wg/issues/92) - update
 
## ISO
- [x] ISO placeholder now available, before its publication- https://www.iso.org/standard/86612.html
> No updates

## Article R&A peer review
- [x] [Use-Case: Automated SCI Measurements with Green Metrics Tool](https://docs.google.com/document/d/1iPLjX0fB6BX1uRPnGwpLr-SaSiwCUBbm/edit)
> Motion - Are there any objections to publishing the Use-Case Article?

## [Case Study Update Review](https://github.com/Green-Software-Foundation/sci-guide/issues?q=is%3Aopen+is%3Aissue+label%3A%22Use+Case%22)   
- [ ] Call for case study submissions. Support & resources are available to all GSF members - Point of contact @seanmcilroy29 

**Note:** 
[WG use case template submission](https://github.com/Green-Software-Foundation/sci-guide/issues/new?assignees=atg-abhishek%2C+Henry-WattTime%2C+navveenb%2C+srini1978&labels=Case-study+submissions&template=case-study-template.md&title=Case-study+submissions) - After submitting this issue, your use case will be submitted to the WG Agenda for discussion.
[Article submission](https://github.com/Green-Software-Foundation/writers/issues/new?assignees=&labels=articles&template=new-article-proposal.md&title=%5BArticle%5D+A+proposed+name+for+this+article+or+topics) - Once you submit this issue, it will be assigned to the GSF Editor to review.

## Future meeting Agenda submissions
- [ ] If you have any Agenda submissions, please let Sean know via email sean@greensoftware.foundation or [open an Issue](https://github.com/Green-Software-Foundation/standards-wg/issues)

## Next Meeting
- [ ] 14th Dec
- [ ] Motion to cancel 28th Dec meeting
- [ ] Motion to move to a bi-weekly cadence 

## Adjourn 
- [ ] Motion to adjourn
--------

## Meeting Action Items / Standing Agenda / Future Agenda submissions
- [ ] Standing Agenda Item - First meeting of each month - Member Introductions / Buddy-buddy meeting to help new members understand the work in the SWG.
- [ ] Standing Agenda Item - First meeting of each month - 5 - 10 min round up of what is happening across the other WG

**Comment by Henry-WattTime** [comment]
Attended

**Comment by tholewis** [comment]
Attended!

**Comment by navveenb** [comment]
Attended

**Comment by seanmcilroy29** [comment]
Attended

**Comment by tmcclell** [comment]
Attended

**Comment by kapokasa** [comment]
Attended

**Comment by GadhuNTTDATA** [comment]
Attended

**Comment by PindyBhullar** [comment]
Attended

**Comment by chargao** [comment]
Attended
