### ISSUE TITLE
2023.01.18

### ISSUE THREAD

**Issue by seanmcilroy29** [Green-Software-Foundation/standards-wg#98]
----
## 2023.01.18 Agenda/Minutes
--- 
Time 1600 (GMT) - See the time in your [timezone](https://everytimezone.com/s/a8399b00)

- Co-Chair - Henry Richards (WattTime)
- Co-Chair - Naveen Balani - (Accenture) 
- Co-Chair – Abhishek Gupta (BCG)
- Convener – Sean Mcilroy (Linux Foundation)

## Antitrust Policy
Joint Development Foundation meetings may involve participation by industry competitors, and the Joint Development Foundation intends to conduct all of its activities in accordance with applicable antitrust and competition laws. It is, therefore, extremely important that attendees adhere to meeting agendas and be aware of and not participate in any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

If you have questions about these matters, please contact your company counsel or counsel to the Joint Development Foundation, DLA Piper.

## Recordings
WG agreed to record all [Meetings](https://docs.google.com/document/d/1WeRybJv8a8vunyRe9AawSqP0feVfe2PJ0KKiAGkI7kQ/edit). This meeting recording will be available until the next scheduled meeting.

## Roll Call 
Please *add 'Attended'* to this issue during the meeting to denote attendance.

Any untracked attendees will be added by the GSF team below:
- Full Name, Affiliation, (optional) GitHub username

## Agenda
- [x] Approve agenda
- [x] Approve [previous Meeting Minutes](https://github.com/Green-Software-Foundation/standards_wg/issues?q=is%3Aopen+is%3Aissue+label%3AAgenda%2FMinutes)

## Member Introductions
- [x] Opportunity for new members to introduce themselves

## GreenAI
- [x] How can this WG help with the increase of AI?

## WG Project updates - [Dashboard](https://github.com/Green-Software-Foundation/standards-wg/issues?q=is%3Aopen+is%3Aissue+label%3A%22Project+Update%22)

- [x] [Organisation usage of Software Emissions](https://github.com/Green-Software-Foundation/standards-wg/issues/91) - update
    - [Collaboration G-Doc](https://docs.google.com/document/d/15BhJo2LPzA49eqQGzXCpksm6ftsUWUBevmXwwyKyzOI/edit)
    - Project to be aligned [Maturity Matrix](https://github.com/Green-Software-Foundation/green-software-maturity-matrix) with project.
- [x] [SCI](https://github.com/Green-Software-Foundation/standards-wg/issues/93) - update
   - New SCI webpage - https://sci.greensoftware.foundation/
- [x] [Software Carbon Efficiency Rating](https://github.com/Green-Software-Foundation/standards-wg/issues/90) - update
    - [Baseline Spec](https://github.com/Green-Software-Foundation/scer/blob/Dev/Software_Carbon_Efficiency_Rating/Software_Carbon_Efficiency_Rating_Specification.md)
    - [Spec Development Proposal and Focus Areas](https://github.com/Green-Software-Foundation/scer/issues/19)
- [x] [Real-Time Cloud](https://github.com/Green-Software-Foundation/standards-wg/issues/89) - update
    - the project has agreed to define the headers from the [GSF Real-Time Cloud Renewable Energy Percentage](https://docs.google.com/spreadsheets/d/1RKjD4CuI5bd7JTj-9Mi1-ZhTIc6OW7TH9hUvLPbLsPA/edit#gid=0) spreadsheet.
    - [collaboration documen](https://docs.google.com/document/d/10sfRbx2lR18I02oNChaLYwc_ZgdtmSh0JyDerNloKGQ/edit#heading=h.4fr2qsg1jh7y)t to create the initial header explanations.
- [ ] [sci-guide](https://github.com/Green-Software-Foundation/standards-wg/issues/92) - update
 
## ISO
- [ ] ISO placeholder now available, before its publication- https://www.iso.org/standard/86612.html
> No updates

## Article R&A peer review
- [ ] UBS usecase in the process of being published

**Note:** 
[WG use case template submission](https://github.com/Green-Software-Foundation/sci-guide/issues/new?assignees=atg-abhishek%2C+Henry-WattTime%2C+navveenb%2C+srini1978&labels=Case-study+submissions&template=case-study-template.md&title=Case-study+submissions) - After submitting this issue, your use case will be submitted to the WG Agenda for discussion.
[Article submission](https://github.com/Green-Software-Foundation/writers/issues/new?assignees=&labels=articles&template=new-article-proposal.md&title=%5BArticle%5D+A+proposed+name+for+this+article+or+topics) - Once you submit this issue, it will be assigned to the GSF Editor to review.

## Future meeting Agenda submissions
- [ ] If you have any Agenda submissions, please let Sean know via email sean@greensoftware.foundation or [open an Issue](https://github.com/Green-Software-Foundation/standards-wg/issues)

## Next Meeting
- [ ] 1st Feb
> Reminder: The Standards WG meeting is moving to a bi-weekly cadence. The meeting series will be updated to reflect this.

## Adjourn 
- [ ] Motion to adjourn
--------

## Meeting Action Items / Standing Agenda / Future Agenda submissions
- [ ] Standing Agenda Item - First meeting of each month - Member Introductions / Buddy-buddy meeting to help new members understand the work in the SWG.
- [ ] Standing Agenda Item - First meeting of each month - 5 - 10 min round up of what is happening across the other WG

**Comment by tholewis** [comment]
Attended!

**Comment by GadhuNTTDATA** [comment]
Attended

**Comment by Henry-WattTime** [comment]
Attended

**Comment by PindyBhullar** [comment]
Attended

**Comment by navveenb** [comment]
attended

**Comment by marcoshidalgonunes-avanade** [comment]
Attended

**Comment by seanmcilroy29** [comment]
Attended

**Comment by filga** [comment]
Attended

**Comment by tmcclell** [comment]
Attended

**Comment by seanmcilroy29** [comment]
Approved

**Comment by PindyBhullar** [comment]
Attended
